[build]
  base = "book"
  command = "python -m pip install --upgrade pip && pip install -r requirements.txt && jupyter-book build --html"
  environment = { PYTHON_VERSION = "3.13" }
  publish = "_build/html"

[[redirects]]
  from = "/*"
  to = "https://eds-book.github.io/:splat"
  status = 200
  force = false